parameters:
    env(SYNOLIA_SCHEDULER_PLUGIN_PING_INTERVAL): 300
    env(SYNOLIA_SCHEDULER_PLUGIN_KEEP_ALIVE): true
    env(SYNOLIA_SCHEDULER_PLUGIN_LOGS_DIR): '%kernel.logs_dir%'
    env(SYNOLIA_SCHEDULER_PLUGIN_TIMEFORMAT_24H): false

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Synolia\SyliusSchedulerCommandPlugin\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,SynoliaSyliusSchedulerCommandPlugin.php}'
